const views=[...document.querySelectorAll('.view')];
const nav=[...document.querySelectorAll('.nav-item')];
const title=document.getElementById('page-title');
const names={dashboard:'Visão geral',orcamentos:'Orçamentos',pedidos:'Pedidos',medicao:'Medição / Conferência',desenho:'Desenho técnico',producao:'Produção',acabamento:'Acabamento',logistica:'Carregamento / Logística',instalacao:'Instalação',clientes:'Clientes',financeiro:'Financeiro',estoque:'Estoque',rh:'RH / Administrativo',documentos:'Documentos',assistente:'Assistente',configuracoes:'Configurações'};
function go(view){views.forEach(v=>v.classList.toggle('active-view',v.id===view));nav.forEach(n=>n.classList.toggle('active',n.dataset.view===view));title.textContent=names[view]||'Visão geral';window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'','#'+view)}
nav.forEach(n=>n.addEventListener('click',()=>go(n.dataset.view)));
document.querySelectorAll('[data-view-link]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.viewLink)));
const today=document.getElementById('today'); if(today) today.textContent=new Intl.DateTimeFormat('pt-BR',{dateStyle:'full'}).format(new Date());
const seed=[{id:'PED-000238',client:'Mariana Costa',job:'Casa Forte',status:'Instalação',measurement:'2026-09-04',install:'2026-09-10',locked:true},{id:'PED-000241',client:'João Silva',job:'Boa Viagem',status:'Em produção',measurement:'2026-09-09',install:'2026-09-12',locked:false},{id:'PED-000242',client:'Studio MN',job:'Graças',status:'Conferência',measurement:'',install:'2026-09-15',locked:false},{id:'PED-000243',client:'Carla Mendes',job:'Pina',status:'Pedido recebido',measurement:'',install:'',locked:false},{id:'PED-000244',client:'Rafael Lima',job:'Olinda',status:'Finalizado',measurement:'2026-08-20',install:'2026-08-28',locked:true}];
let orders=JSON.parse(localStorage.getItem('porcelane.orders')||'null')||seed;
let budgets=JSON.parse(localStorage.getItem('porcelane.budgets')||'null')||[];
let clients=JSON.parse(localStorage.getItem('porcelane.clients')||'null')||[];
const stages=['Pedido recebido','Conferência','Em produção','Instalação','Finalizado'];
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const save=()=>{localStorage.setItem('porcelane.orders',JSON.stringify(orders));localStorage.setItem('porcelane.budgets',JSON.stringify(budgets));localStorage.setItem('porcelane.clients',JSON.stringify(clients))};
function card(o){return `<div class="order-card" data-order="${esc(o.id)}"><strong>${esc(o.id)}</strong><span>${esc(o.client)}</span><span>${esc(o.job)}</span>${o.measurement?'<small class="ok">Medição registrada</small>':'<small class="warning">Medição pendente</small>'}<small>${o.locked?'Pedido protegido':'Clique para abrir'}</small></div>`}
function renderOrders(){const board=document.getElementById('orders-board');if(!board)return;board.innerHTML=stages.map(stage=>`<div class="kanban-col"><h4>${stage}<em>${orders.filter(o=>o.status===stage).length}</em></h4>${orders.filter(o=>o.status===stage).map(card).join('')||'<div class="empty">Nenhum pedido</div>'}</div>`).join('');document.getElementById('recent-orders').innerHTML=orders.slice(0,4).map(card).join('');document.querySelectorAll('[data-order]').forEach(c=>c.onclick=()=>openOrder(c.dataset.order));renderOperationalQueues()}
function renderMetrics(){const active=orders.filter(o=>o.status!=='Finalizado').length;const production=orders.filter(o=>o.status==='Em produção').length;const installs=orders.filter(o=>o.status==='Instalação').length;const budgetsOpen=budgets.filter(b=>b.status!=='Aprovado'&&b.status!=='Recusado').length;const m=document.getElementById('dashboard-metrics');if(m)m.innerHTML=[['Pedidos em andamento',active,'Atualizados agora'],['Em produção',production,'Acompanhamento da fábrica'],['Instalações próximas',installs,'Próximos 7 dias'],['Orçamentos abertos',budgetsOpen,'Aguardando retorno']].map(x=>`<article class="metric"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('')}
function modal(title,body,onSubmit){const old=document.getElementById('porcelane-modal');if(old)old.remove();const d=document.createElement('dialog');d.id='porcelane-modal';d.innerHTML=`<form method="dialog" class="panel" style="min-width:min(620px,92vw)"><div class="panel-head"><h3>${title}</h3><button value="cancel">×</button></div>${body}<div style="display:flex;gap:10px;justify-content:flex-end;margin-top:20px"><button value="cancel">Cancelar</button><button class="primary" id="modal-ok" value="default">Salvar</button></div></form>`;document.body.appendChild(d);d.querySelector('#modal-ok').onclick=e=>{e.preventDefault();if(onSubmit(d))d.close()};d.showModal()}
function openOrder(id){const o=orders.find(x=>x.id===id);if(!o)return;const canProduce=!!o.measurement;modal(`Pedido ${o.id}`,`<p><strong>${esc(o.client)}</strong> · ${esc(o.job)}</p><label>Status<select id="m-status">${stages.map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Data de medição<input id="m-measure" type="date" value="${o.measurement||''}"></label><label>Instalação<input id="m-install" type="date" value="${o.install||''}"></label><p class="${canProduce?'ok':'warning'}">${canProduce?'Medição registrada: produção pode ser liberada.':'Sem data de medição: produção permanece BLOQUEADA.'}</p>`,d=>{const ns=d.querySelector('#m-status').value;const nm=d.querySelector('#m-measure').value;if(o.locked){alert('Este pedido está fechado e protegido contra alteração.');return false}if((ns==='Em produção'||ns==='Instalação')&&!nm){alert('Não é possível avançar este pedido para produção ou instalação sem uma data de medição registrada.');return false}if(ns==='Finalizado'&&(!nm||!d.querySelector('#m-install').value)){alert('Para finalizar, registre a medição e a data de instalação.');return false}o.status=ns;o.measurement=nm;o.install=d.querySelector('#m-install').value;o.locked=ns==='Finalizado';save();renderOrders();renderMetrics();return true})}
function newOrder(){modal('Novo pedido',`<label>Cliente<input id="f-client" required placeholder="Nome do cliente"></label><label>Obra / local<input id="f-job" required placeholder="Ex.: Casa Forte"></label><label>Data de medição<input id="f-measure" type="date"></label><label>Data de instalação<input id="f-install" type="date"></label>`,d=>{const client=d.querySelector('#f-client').value.trim(),job=d.querySelector('#f-job').value.trim();if(!client||!job)return false;const next=Math.max(244,...orders.map(o=>Number(o.id.replace(/\D/g,''))||0))+1;orders.unshift({id:`PED-${String(next).padStart(6,'0')}`,client,job,measurement:d.querySelector('#f-measure').value,install:d.querySelector('#f-install').value,status:'Pedido recebido',locked:false});save();renderOrders();renderMetrics();go('pedidos');return true})}
function newBudget(){modal('Novo orçamento',`<label>Cliente<input id="b-client" required></label><label>Obra<input id="b-job" required></label><label>M²<input id="b-m2" type="number" min="0" step="0.01"></label><label>Valor<input id="b-value" type="number" min="0" step="0.01"></label>`,d=>{const client=d.querySelector('#b-client').value.trim(),job=d.querySelector('#b-job').value.trim();if(!client||!job)return false;const n=budgets.length+127;budgets.unshift({id:`ORC-${String(n).padStart(6,'0')}`,client,job,m2:d.querySelector('#b-m2').value,value:d.querySelector('#b-value').value,status:'Em elaboração'});save();renderOrders();renderMetrics();alert('Orçamento criado.');return true})}
function newClient(){modal('Novo cliente',`<label>Nome<input id="c-name" required></label><label>Telefone<input id="c-phone"></label><label>Obra / observação<textarea id="c-note"></textarea></label>`,d=>{const name=d.querySelector('#c-name').value.trim();if(!name)return false;clients.unshift({name,phone:d.querySelector('#c-phone').value,note:d.querySelector('#c-note').value});save();alert('Cliente cadastrado.');return true})}
function renderOperationalQueues(){
 const measurement=document.querySelector('#medicao .panel-body')||document.querySelector('#medicao .panel');
 const production=document.querySelector('#producao .panel-body')||document.querySelector('#producao .panel');
 if(measurement){let box=document.getElementById('dynamic-measurement-queue');if(!box){box=document.createElement('div');box.id='dynamic-measurement-queue';box.className='list';measurement.appendChild(box)}box.innerHTML=orders.filter(o=>o.status!=='Finalizado').map(o=>`<div class="list-row"><strong>${esc(o.id)}</strong><span>${esc(o.client)} · ${esc(o.job)}</span><span class="badge ${o.measurement?'green':'amber'}">${o.measurement?'Medição registrada':'Aguardando medição'}</span><button data-open-order="${esc(o.id)}">${o.measurement?'Abrir':'Registrar'}</button></div>`).join('')||'<div class="empty">Nenhum pedido pendente.</div>';box.querySelectorAll('[data-open-order]').forEach(b=>b.onclick=()=>openOrder(b.dataset.openOrder))}
 if(production){let box=document.getElementById('dynamic-production-queue');if(!box){box=document.createElement('div');box.id='dynamic-production-queue';box.className='list';production.appendChild(box)}box.innerHTML=orders.filter(o=>o.status==='Em produção').map(o=>`<div class="list-row"><strong>${esc(o.id)}</strong><span>${esc(o.client)} · ${esc(o.job)}</span><span class="badge green">Liberado para produção</span><button data-open-order="${esc(o.id)}">Abrir</button></div>`).join('')||'<div class="empty">Nenhum pedido liberado para produção.</div>';box.querySelectorAll('[data-open-order]').forEach(b=>b.onclick=()=>openOrder(b.dataset.openOrder))}
}
renderOrders();renderMetrics();
document.getElementById('new-order')?.addEventListener('click',newOrder);document.getElementById('new-order-2')?.addEventListener('click',newOrder);document.getElementById('new-budget')?.addEventListener('click',newBudget);
const clientButtons=[...document.querySelectorAll('#clientes .primary')];clientButtons.forEach(b=>b.addEventListener('click',newClient));
document.querySelectorAll('[data-assist]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.assist;const result=document.getElementById('assistant-result');if(!result)return;const text={pedidos:`Há ${orders.filter(o=>o.status!=='Finalizado').length} pedidos em andamento.`,medicao:`Há ${orders.filter(o=>!o.measurement).length} pedidos sem data de medição. Eles não podem ser liberados para produção.`,producao:`Há ${orders.filter(o=>o.status==='Em produção').length} pedidos em produção.`,financeiro:'Use os lançamentos do módulo Financeiro para controlar contas a receber, parcelas e comissões.'};result.textContent=text[key]||'Tudo certo.'}));
document.getElementById('clear-local')?.addEventListener('click',()=>{if(confirm('Apagar os pedidos criados neste dispositivo?')){localStorage.removeItem('porcelane.orders');orders=[...seed];renderOrders();renderMetrics()}});
const finish=[['PED-000241','Borda reta · polimento'],['PED-000242','Colagem · conferência'],['PED-000238','Acabamento final']];const fl=document.getElementById('finish-list');if(fl)fl.innerHTML=finish.map(x=>`<div class="list-row"><strong>${x[0]}</strong><span>${x[1]}</span><span class="badge amber">Em andamento</span></div>`).join('');
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
if(location.hash&&names[location.hash.slice(1)])go(location.hash.slice(1));