import { createClient } from '@supabase/supabase-js';
import './documentos-upload.css';

const db = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY);
const BUCKET = 'pedidos-fechados';
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
async function empresaAtual(){const {data:{user}}=await db.auth.getUser();if(!user?.email)return null;const {data}=await db.from('perfis').select('empresa_id').ilike('email',user.email).eq('ativo',true).maybeSingle();return data?.empresa_id||null;}
function safeName(name){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'_');}
async function uploadPdf(pedidoId,file){if(file.type!=='application/pdf'){alert('Selecione um arquivo PDF.');return false}if(file.size>25*1024*1024){alert('O PDF deve ter no máximo 25 MB.');return false}const empresaId=await empresaAtual();if(!empresaId){alert('Não foi possível identificar a empresa do usuário logado.');return false}const path=`${empresaId}/pedidos/${pedidoId}/${Date.now()}-${safeName(file.name)}`;const {error:uploadError}=await db.storage.from(BUCKET).upload(path,file,{contentType:'application/pdf',upsert:false});if(uploadError){alert('Não foi possível carregar o PDF: '+uploadError.message);return false}const {data:{user}}=await db.auth.getUser();const {data:doc,error:docError}=await db.from('documentos').insert({pedido_id:pedidoId,tipo:'pdf',titulo:file.name,status:'ativo',arquivo_url:path}).select('id').single();if(docError){await db.storage.from(BUCKET).remove([path]);alert('O PDF foi enviado, mas não foi possível registrar o documento: '+docError.message);return false}await db.from('documento_versoes').insert({documento_id:doc.id,versao:1,arquivo_url:path,criado_por:user?.id||null});alert('PDF carregado e registrado no pedido.');await renderUploaded(pedidoId);return true}
async function signedPdf(path){const {data,error}=await db.storage.from(BUCKET).createSignedUrl(path,300);if(error||!data?.signedUrl){alert('Não foi possível preparar o PDF: '+(error?.message||'URL indisponível'));return null}return data.signedUrl}
async function sharePdf(path,title){const signedUrl=await signedPdf(path);if(!signedUrl)return false;try{const response=await fetch(signedUrl);if(!response.ok)throw new Error('Não foi possível carregar o arquivo.');const blob=await response.blob();const file=new File([blob],safeName(title||'documento.pdf'),{type:'application/pdf'});if(!navigator.share||!navigator.canShare||!navigator.canShare({files:[file]})){alert('O compartilhamento de PDF não é compatível neste navegador. No celular, abra o Porcelane no Chrome/Android para enviar diretamente pelo WhatsApp sem salvar o arquivo.');return false}await navigator.share({files:[file],title:title||'Documento Porcelane',text:'Documento enviado pelo Porcelane.'});return true}catch(error){if(error?.name==='AbortError')return false;alert('Não foi possível compartilhar o PDF: '+error.message);return false}}
async function renderUploaded(pedidoId){const host=document.querySelector(`[data-uploaded-docs="${pedidoId}"]`);if(!host)return;const {data,error}=await db.from('documentos').select('id,titulo,arquivo_url,criado_em').eq('pedido_id',pedidoId).not('arquivo_url','is',null).order('criado_em',{ascending:false});if(error){host.innerHTML='';return}host.innerHTML=(data||[]).map(d=>`<div class="doc-file-row"><button class="doc-file" data-doc-path="${esc(d.arquivo_url)}">📄 ${esc(d.titulo)}</button><button class="doc-share-whatsapp" data-share-path="${esc(d.arquivo_url)}" data-share-title="${esc(d.titulo)}" type="button">📲 Enviar WhatsApp</button></div>`).join('');host.querySelectorAll('[data-doc-path]').forEach(b=>b.onclick=async()=>{const signedUrl=await signedPdf(b.dataset.docPath);if(signedUrl)window.open(signedUrl,'_blank','noopener,noreferrer')});host.querySelectorAll('[data-share-path]').forEach(b=>b.onclick=()=>sharePdf(b.dataset.sharePath,b.dataset.shareTitle))}
function enhance(){document.querySelectorAll('#documentos .doc-grid .panel').forEach(panel=>{if(panel.dataset.pdfReady)return;const strong=panel.querySelector('strong');const buttons=panel.querySelectorAll('[data-doc]');if(!strong||!buttons.length)return;const pedidoId=buttons[0].dataset.id;panel.dataset.pdfReady='1';const wrap=document.createElement('div');wrap.className='pdf-upload-area';wrap.innerHTML=`<label class="pdf-upload-label">Carregar PDF<input type="file" accept="application/pdf" data-pdf-upload="${esc(pedidoId)}"></label><div class="uploaded-docs" data-uploaded-docs="${esc(pedidoId)}"></div>`;panel.appendChild(wrap);wrap.querySelector('input').onchange=async e=>{const file=e.target.files?.[0];if(file)await uploadPdf(pedidoId,file);e.target.value=''};renderUploaded(pedidoId)})}
window.addEventListener('load',()=>{enhance();setInterval(enhance,1200)});
window.PorcelaneDocumentos={uploadPdf,sharePdf};
