import { createClient } from '@supabase/supabase-js';

const url = import.meta.env.VITE_SUPABASE_URL;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
const db = createClient(url, key);
const esc = v => String(v ?? '').replace(/[&<>\"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const brDate = v => v ? new Date(`${v}T12:00:00`).toLocaleDateString('pt-BR') : '—';
const money = v => Number(v || 0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

async function loadProduction(){
  const {data,error}=await db.from('ordens_producao').select('id,numero,status,data_liberacao,data_inicio,data_conclusao,observacoes,pedido_id,pedido:pedidos(numero,cliente:clientes(nome))').order('criado_em',{ascending:false});
  if(error){console.warn(error);return []} return data||[];
}
async function loadCuts(){
  const {data,error}=await db.from('ordens_corte').select('id,pedido_id,ordem_producao_id,status,data_liberacao,data_corte,operador,observacoes,pedido:pedidos(numero,cliente:clientes(nome))').order('criado_em',{ascending:false});
  if(error){console.warn(error);return []} return data||[];
}
async function loadMaterials(){
  const {data,error}=await db.from('materiais').select('id,nome,unidade,estoque,estoque_minimo,custo,preco').eq('ativo',true).order('nome');
  if(error){console.warn(error);return []} return data||[];
}
async function loadReservations(){
  const {data,error}=await db.from('reservas_estoque').select('id,pedido_id,ordem_producao_id,material_id,quantidade,status,criado_em,material:materiais(nome,unidade),pedido:pedidos(numero,cliente:clientes(nome))').order('criado_em',{ascending:false});
  if(error){console.warn(error);return []} return data||[];
}
function panel(title,body){return `<div class="panel"><div class="panel-head"><h3>${title}</h3></div>${body}</div>`}
function rows(items,empty,mapper){return items.length?items.map(mapper).join(''): `<div class="empty">${empty}</div>`}
function printDocument(title, content){
  const w=window.open('','_blank','noopener,noreferrer,width=900,height=700');
  if(!w){alert('Permita pop-ups para gerar o documento.');return}
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4;margin:14mm}body{font-family:Arial,sans-serif;color:#161616;font-size:12px;line-height:1.45}h1{font-size:22px;margin:0 0 6px}h2{font-size:15px;border-bottom:1px solid #bbb;padding-bottom:5px;margin-top:20px}.meta{color:#555;margin-bottom:18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.box{border:1px solid #ccc;border-radius:6px;padding:10px}table{width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid #ddd;padding:7px}th{font-size:11px;text-transform:uppercase}.signature{margin-top:55px;display:grid;grid-template-columns:1fr 1fr;gap:50px}.line{border-top:1px solid #222;padding-top:5px;text-align:center}</style></head><body><h1>${esc(title)}</h1><div class="meta">Porcelane · ${new Date().toLocaleDateString('pt-BR')}</div>${content}<script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close();
}
function documentButtons(order){
  const numero=order?.numero||'Pedido'; const cliente=order?.cliente?.nome||'';
  return `<div style="display:flex;gap:8px;flex-wrap:wrap;margin:10px 0"><button data-print-order>Imprimir pedido</button><button data-print-delivery>Protocolo retirada/entrega</button></div>`;
}
async function render(){
  const [ops,cuts,mats,reservas]=await Promise.all([loadProduction(),loadCuts(),loadMaterials(),loadReservations()]);
  const prod=document.querySelector('#producao .production-grid');
  if(prod){
    const cards=ops.map(op=>`<div class="list-row"><strong>${esc(op.numero||'OP')}</strong><span>${esc(op.pedido?.numero||'')} · ${esc(op.pedido?.cliente?.nome||'')}</span><span class="badge ${op.status==='concluida'?'green':'amber'}">${esc(op.status||'liberada')}</span><button data-op="${op.id}">Abrir</button></div>`).join('')||'<div class="empty">Nenhuma ordem de produção.</div>';
    prod.innerHTML=panel('Ordens de produção',`<div class="list">${cards}</div>`)+panel('Corte / PCP',`<div class="list">${rows(cuts,'Nenhuma ordem de corte.',c=>`<div class="list-row"><strong>${esc(c.pedido?.numero||'Corte')}</strong><span>${esc(c.pedido?.cliente?.nome||'')}</span><span class="badge ${c.status==='concluida'?'green':'amber'}">${esc(c.status||'liberada')}</span><span>${brDate(c.data_liberacao)}</span><button data-cut="${c.id}">Abrir</button></div>`)}</div>`);
    prod.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>openOP(ops.find(x=>x.id===b.dataset.op)));
    prod.querySelectorAll('[data-cut]').forEach(b=>b.onclick=()=>openCut(cuts.find(x=>x.id===b.dataset.cut)));
  }
  const finish=document.querySelector('#acabamento .panel');
  if(finish) finish.innerHTML=`<div class="panel-head"><h3>Fila de acabamento</h3></div><div class="list">${rows(ops.filter(o=>o.status==='concluida'),'Nenhuma ordem pronta para acabamento.',o=>`<div class="list-row"><strong>${esc(o.numero)}</strong><span>${esc(o.pedido?.cliente?.nome||'')}</span><span class="badge green">Pronta para acabamento</span></div>`)}</div>`;
  const log=document.querySelector('#logistica .panel');
  if(log){const {data}=await db.from('entregas').select('id,pedido_id,data_agendada,hora_inicio,hora_fim,status,endereco,responsavel,pedido:pedidos(numero,cliente:clientes(nome))').order('data_agendada',{ascending:true});log.innerHTML=`<div class="panel-head"><h3>Agenda de carregamento e entrega</h3></div><div class="list">${rows(data||[],'Nenhuma entrega agendada.',e=>`<div class="list-row"><strong>${esc(e.pedido?.numero||'Entrega')}</strong><span>${esc(e.pedido?.cliente?.nome||'')}</span><span>${brDate(e.data_agendada)} ${e.hora_inicio?esc(e.hora_inicio):''}</span><span class="badge amber">${esc(e.status||'agendada')}</span><button data-delivery-print="${e.id}">Protocolo</button></div>`)}</div>`;log.querySelectorAll('[data-delivery-print]').forEach(b=>b.onclick=()=>{const e=(data||[]).find(x=>x.id===b.dataset.deliveryPrint);printDelivery(e)});}
  const inst=document.querySelector('#instalacao .panel');
  if(inst){const {data}=await db.from('instalacoes').select('id,pedido_id,data_agendada,hora_inicio,hora_fim,status,instalador,observacoes,pedido:pedidos(numero,cliente:clientes(nome))').order('data_agendada',{ascending:true});inst.innerHTML=`<div class="panel-head"><h3>Agenda de instalação</h3></div><div class="list">${rows(data||[],'Nenhuma instalação agendada.',i=>`<div class="list-row"><strong>${esc(i.pedido?.numero||'Instalação')}</strong><span>${esc(i.pedido?.cliente?.nome||'')}</span><span>${brDate(i.data_agendada)} ${i.hora_inicio?esc(i.hora_inicio):''}</span><span class="badge ${i.status==='concluida'?'green':'amber'}">${esc(i.status||'agendada')}</span><span>${esc(i.instalador||'')}</span></div>`)}</div>`}
  const stock=document.querySelector('#estoque .panel')||document.querySelector('#estoque');
  if(stock){
    stock.innerHTML=panel('Estoque operacional',`<div style="display:flex;justify-content:flex-end;margin-bottom:10px"><button class="primary" id="reserve-stock">Reservar material</button></div><div class="table-panel"><table><thead><tr><th>Material</th><th>Unid.</th><th>Estoque</th><th>Mínimo</th><th>Preço</th><th></th></tr></thead><tbody>${rows(mats,'Nenhum material cadastrado.',m=>`<tr><td>${esc(m.nome)}</td><td>${esc(m.unidade||'—')}</td><td>${Number(m.estoque||0)}</td><td>${Number(m.estoque_minimo||0)}</td><td>${money(m.preco)}</td><td>${Number(m.estoque||0)<=Number(m.estoque_minimo||0)?'<span class="badge amber">Repor</span>':'<span class="badge green">OK</span>'}</td></tr>`)}</tbody></table></div>`+panel('Reservas de material',`<div class="list">${rows(reservas,'Nenhuma reserva registrada.',r=>`<div class="list-row"><strong>${esc(r.material?.nome||'Material')}</strong><span>${esc(r.pedido?.numero||'')}</span><span>${Number(r.quantidade)} ${esc(r.material?.unidade||'')}</span><span class="badge ${r.status==='consumido'?'green':r.status==='cancelado'?'':'amber'}">${esc(r.status)}</span>${r.status==='reservado'?`<button data-consume="${r.id}">Consumir</button><button data-cancel="${r.id}">Cancelar</button>`:''}</div>`)}</div>`));
    document.getElementById('reserve-stock')?.addEventListener('click',()=>openReservation(mats,ops));
    stock.querySelectorAll('[data-consume]').forEach(b=>b.onclick=()=>consumeReservation(b.dataset.consume));
    stock.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>cancelReservation(b.dataset.cancel));
  }
}
function dialog(title,body,save){const old=document.getElementById('pcp-dialog');old?.remove();const d=document.createElement('dialog');d.id='pcp-dialog';d.innerHTML=`<form method="dialog" class="panel" style="min-width:min(680px,92vw)"><div class="panel-head"><h3>${title}</h3><button value="cancel">×</button></div>${body}<div style="display:flex;justify-content:flex-end;gap:10px;margin-top:18px"><button value="cancel">Cancelar</button><button class="primary" id="pcp-save">Salvar</button></div></form>`;document.body.appendChild(d);d.querySelector('#pcp-save').onclick=async e=>{e.preventDefault();if(await save(d))d.close()};d.showModal()}
async function openOP(op){if(!op)return;dialog(`Ordem ${op.numero}`,`<p><strong>${esc(op.pedido?.numero||'')}</strong> · ${esc(op.pedido?.cliente?.nome||'')}</p><label>Status<select id="s"><option ${op.status==='liberada'?'selected':''}>liberada</option><option ${op.status==='em_producao'?'selected':''}>em_producao</option><option ${op.status==='concluida'?'selected':''}>concluida</option></select></label><label>Observações<textarea id="n">${esc(op.observacoes||'')}</textarea></label>`,async d=>{const s=d.querySelector('#s').value;const patch={status:s,observacoes:d.querySelector('#n').value||null};if(s==='em_producao'&&!op.data_inicio)patch.data_inicio=new Date().toISOString().slice(0,10);if(s==='concluida')patch.data_conclusao=new Date().toISOString().slice(0,10);const {error}=await db.from('ordens_producao').update(patch).eq('id',op.id);if(error){alert(error.message);return false}await render();return true})}
async function openCut(c){if(!c)return;dialog(`Ordem de corte — ${c.pedido?.numero||''}`,`<p><strong>${esc(c.pedido?.cliente?.nome||'')}</strong></p><label>Status<select id="s"><option ${c.status==='liberada'?'selected':''}>liberada</option><option ${c.status==='em_corte'?'selected':''}>em_corte</option><option ${c.status==='concluida'?'selected':''}>concluida</option></select></label><label>Operador<input id="o" value="${esc(c.operador||'')}"></label><label>Observações<textarea id="n">${esc(c.observacoes||'')}</textarea></label>`,async d=>{const s=d.querySelector('#s').value;const patch={status:s,operador:d.querySelector('#o').value||null,observacoes:d.querySelector('#n').value||null};if(s==='concluida')patch.data_corte=new Date().toISOString().slice(0,10);const {error}=await db.from('ordens_corte').update(patch).eq('id',c.id);if(error){alert(error.message);return false}await render();return true})}
function openReservation(mats,ops){const options=mats.map(m=>`<option value="${m.id}">${esc(m.nome)} — disponível ${Number(m.estoque||0)} ${esc(m.unidade||'')}</option>`).join('');const opOptions=ops.map(o=>`<option value="${o.id}" data-pedido="${o.pedido_id}">${esc(o.numero)} · ${esc(o.pedido?.cliente?.nome||'')}</option>`).join('');dialog('Reservar material',`<label>Ordem de produção<select id="op">${opOptions||'<option value="">Nenhuma OP</option>'}</select></label><label>Material<select id="m">${options}</select></label><label>Quantidade<input id="q" type="number" min="0.001" step="0.001" value="1"></label><p class="muted">A reserva não baixa o estoque físico. O consumo é a etapa que efetivamente baixa o saldo.</p>`,async d=>{const op=d.querySelector('#op').selectedOptions[0];const material=mats.find(m=>m.id===d.querySelector('#m').value);const q=Number(d.querySelector('#q').value);if(!material||!q||q<=0){alert('Informe material e quantidade.');return false}if(q>Number(material.estoque||0)){alert('Quantidade maior que o estoque disponível.');return false}const {error}=await db.from('reservas_estoque').insert({pedido_id:op?.dataset.pedido||null,ordem_producao_id:op?.value||null,material_id:material.id,quantidade:q,status:'reservado'});if(error){alert(error.message);return false}await render();return true})}
async function consumeReservation(id){if(!confirm('Consumir esta reserva e baixar o estoque?'))return;const {data:r,error}=await db.from('reservas_estoque').select('id,material_id,quantidade,status').eq('id',id).single();if(error||!r){alert(error?.message||'Reserva não encontrada.');return}if(r.status!=='reservado')return;const {data:m,error:me}=await db.from('materiais').select('id,estoque').eq('id',r.material_id).single();if(me||!m){alert(me?.message||'Material não encontrado.');return}const novo=Number(m.estoque||0)-Number(r.quantidade||0);if(novo<0){alert('Estoque insuficiente para consumir esta reserva.');return}const {error:ue}=await db.from('materiais').update({estoque:novo}).eq('id',m.id);if(ue){alert(ue.message);return}const {error:re}=await db.from('reservas_estoque').update({status:'consumido'}).eq('id',id);if(re){alert(re.message);return}await render()}
async function cancelReservation(id){if(!confirm('Cancelar esta reserva?'))return;const {error}=await db.from('reservas_estoque').update({status:'cancelado'}).eq('id',id);if(error){alert(error.message);return}await render()}
function printDelivery(e){if(!e)return;printDocument(`PROTOCOLO DE ${e.tipo==='retirada'?'RETIRADA':'ENTREGA'}`,`<div class="grid"><div class="box"><b>Pedido</b><br>${esc(e.pedido?.numero||'—')}</div><div class="box"><b>Cliente</b><br>${esc(e.pedido?.cliente?.nome||'—')}</div><div class="box"><b>Data</b><br>${brDate(e.data_agendada)}</div><div class="box"><b>Responsável</b><br>${esc(e.responsavel||'—')}</div></div><h2>Conferência</h2><div class="box">Material/produtos conferidos · volumes conferidos · estado da peça conferido · documentação entregue.</div><div class="signature"><div class="line">Responsável Porcelane</div><div class="line">Cliente / responsável pelo recebimento</div></div>`)}
window.addEventListener('load',()=>setTimeout(render,1100));
window.addEventListener('hashchange',()=>setTimeout(render,250));