import { createClient } from '@supabase/supabase-js';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const types={interno:'Funcionário interno',externo:'Funcionário externo / prestador',arquiteto:'Arquiteto / parceiro',comercial:'Comercial / vendedor',outro:'Outro'};
const roles={admin:'Administrador',vendas:'Vendas',tecnico:'Técnico',pcp:'PCP',financeiro:'Financeiro',rh:'RH / Administrativo',instalacao:'Instalação',cliente:'Cliente'};
const modules=[['orcamentos','Orçamentos'],['pedidos','Pedidos'],['medicao','Medição'],['liberacao_tecnica','Liberação Técnica'],['desenho','Desenho Técnico'],['producao','Produção'],['acabamento','Acabamento'],['logistica','Logística'],['instalacao','Instalação'],['clientes','Clientes'],['financeiro','Financeiro'],['estoque','Estoque'],['rh','RH / Administrativo'],['documentos','Documentos'],['assistente','Assistente']];
let people=[];
function field(label,id,type='text',extra=''){return `<label>${label}<input id="${id}" type="${type}" ${extra}></label>`}
function formPerson(p={}){const access=p.acesso||{};return `<div class="grid-2"><div>${field('Nome completo','p-name','text',`value="${esc(p.nome||'')}" required`)}${field('E-mail','p-email','email',`value="${esc(p.email||'')}"`)}${field('Telefone / WhatsApp','p-phone','text',`value="${esc(p.telefone||'')}"`)}${field('Cargo / função','p-cargo','text',`value="${esc(p.cargo||'')}"`)}${field('Data de entrada','p-entry','date',`value="${esc(p.data_entrada||'')}"`)}<label>Tipo de pessoa<select id="p-type">${Object.entries(types).map(([k,v])=>`<option value="${k}" ${p.tipo===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Perfil de acesso<select id="p-role">${Object.entries(roles).map(([k,v])=>`<option value="${k}" ${p.role===k?'selected':''}>${v}</option>`).join('')}</select></label></div><div><label>Percentual de comissão<input id="p-commission" type="number" min="0" max="100" step="0.01" value="${Number(p.comissao_percentual||0)}"></label><label>Regra de comissão<select id="p-rule"><option value="individual">Percentual individual</option><option value="amanda">Comercial — regra por faturamento</option><option value="arquiteto">Arquiteto / parceiro</option><option value="nenhuma">Sem comissão</option></select></label><label>Produtividade medida por<select id="p-productivity"><option value="atividade">Atividades concluídas</option><option value="pedido">Pedidos concluídos</option><option value="producao">Produção executada</option><option value="instalacao">Instalações concluídas</option><option value="nao_aplica">Não se aplica</option></select></label><label>Supervisor / responsável<input id="p-supervisor" type="text" value="${esc(p.supervisor||'')}"></label><label>Observações<textarea id="p-notes" rows="4">${esc(p.observacoes||'')}</textarea></label></div></div><div class="panel" style="margin-top:15px"><h3>Acessos liberados</h3><div class="settings-grid">${modules.map(([k,v])=>`<label style="padding:8px 0"><input type="checkbox" data-access="${k}" ${access[k]?'checked':''}> ${v}</label>`).join('')}</div></div>`}
async function load(){const list=document.getElementById('hr-list');if(!list)return;const {data,error}=await supabase.from('colaboradores').select('*').order('nome');if(error){list.innerHTML=`<div class="empty">O cadastro de equipe ainda precisa da tabela <strong>colaboradores</strong> no Supabase. A estrutura SQL está em <strong>supabase/migrations/20260914_people_productivity.sql</strong>.</div>`;return}people=data||[];render();}
function render(){const list=document.getElementById('hr-list');if(!list)return;list.innerHTML=`<div class="panel-head"><h3>Equipe e parceiros</h3><button class="primary" id="new-person">Novo cadastro</button></div>${people.length?people.map(p=>`<div class="list-row"><div><strong>${esc(p.nome)}</strong><br><small>${esc(types[p.tipo]||p.tipo||'')} · ${esc(p.cargo||'')}</small></div><span>${esc(roles[p.role]||p.role||'')} · ${Number(p.comissao_percentual||0).toLocaleString('pt-BR')}% comissão</span><span class="badge ${p.ativo===false?'amber':'green'}">${p.ativo===false?'Inativo':'Ativo'}</span><button data-edit-person="${p.id}">Editar</button></div>`).join(''):'<div class="empty">Nenhum colaborador ou parceiro cadastrado.</div>'}`;document.getElementById('new-person').onclick=()=>openForm();list.querySelectorAll('[data-edit-person]').forEach(b=>b.onclick=()=>openForm(people.find(p=>p.id===b.dataset.editPerson)));}
function openForm(person){const old=document.getElementById('person-modal');old?.remove();const d=document.createElement('dialog');d.id='person-modal';d.innerHTML=`<form class="panel" style="min-width:min(850px,94vw)"><div class="panel-head"><h3>${person?'Editar cadastro':'Novo cadastro de pessoa'}</h3><button type="button" id="person-close">×</button></div>${formPerson(person||{})}<div class="dialog-actions"><button type="button" id="person-cancel">Cancelar</button><button class="primary" type="submit">Salvar cadastro</button></div></form>`;document.body.appendChild(d);d.showModal();d.querySelector('#person-close').onclick=d.querySelector('#person-cancel').onclick=()=>d.close();d.querySelector('form').onsubmit=async e=>{e.preventDefault();const acesso={};d.querySelectorAll('[data-access]').forEach(x=>acesso[x.dataset.access]=x.checked);const payload={nome:d.querySelector('#p-name').value.trim(),email:d.querySelector('#p-email').value.trim()||null,telefone:d.querySelector('#p-phone').value.trim()||null,cargo:d.querySelector('#p-cargo').value.trim()||null,data_entrada:d.querySelector('#p-entry').value||null,tipo:d.querySelector('#p-type').value,role:d.querySelector('#p-role').value,comissao_percentual:Number(d.querySelector('#p-commission').value)||0,regra_comissao:d.querySelector('#p-rule').value,regra_produtividade:d.querySelector('#p-productivity').value,supervisor:d.querySelector('#p-supervisor').value.trim()||null,observacoes:d.querySelector('#p-notes').value.trim()||null,acesso,ativo:true};const q=person?supabase.from('colaboradores').update(payload).eq('id',person.id):supabase.from('colaboradores').insert(payload);const {error}=await q;if(error){alert('Não foi possível salvar: '+error.message);return}d.close();await load();};}
window.addEventListener('porcelane:rh',load);setTimeout(load,0);
